service: slack-notifier

frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: ap-northeast-1

functions:
  sentry:
    handler: handler.sentry
    events:
      - http:
          path: /sentry
          method: post
    environment:
      SLACK_WEBHOOK_URL: ${ssm:/slack-notifier/slack_webhook_url}
