name: CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/SlackNotifierRole
          aws-region: ap-northeast-1

      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Deploy to AWS Lambda and API Gateway
        run: sls deploy
